name: ci-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk17
          arguments: build

  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Qodana
        uses: JetBrains/qodana-action@v3.2.1
        with:
          linter: qodana-jvm-community
          fail-threshold: 10

      - name: Upload Qodana report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: qodana-report
          path: ${{ github.workspace }}/qodana
